version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/orion0616/sealion
    steps:
      - checkout
      - run: go test github.com/orion0616/sealion/...
